apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kawindelivery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kawindelivery
  minReplicas: 1
  maxReplicas: 3
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageValue: 10Mi 
